# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubEndpointTDD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubEndpointTDD
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'Moya/RxSwift', '~> 13.0'
    pod 'Alamofire'
    pod 'RxRealm'
    pod 'MJRefresh'
    
  target 'GithubEndpointTDDTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest', '~> 4.0'
    
  end

  target 'GithubEndpointTDDUITests' do
    # Pods for testing
  end

end
